### ISSUE TITLE
Where is the dataset?

### ISSUE THREAD

**Issue by w5688414** [SCHENLIU/Bert-Hierarchical-Softmax-Chinese-Text-Classification#1]
Can anyone provide the dataset used in the repo?

**Comment by SCHENLIU** [comment]
> Can anyone provide the dataset used in the repo?

hi, sorry that the original dadaset cannot be provided for some reasons, but there have alternatives pulblic dataset you can experiment, like:
http://thuctc.thunlp.org/#%E8%8E%B7%E5%8F%96%E9%93%BE%E6%8E%A5

**Comment by w5688414** [comment]
@SCHENLIU 
can you show some samples of the dataset? If you provide some sample, I can understand the code more clearly, and quickly modify your code for my own experiments

**Comment by SCHENLIU** [comment]
Sure, some samples are loaded here:
https://github.com/SCHENLIU/Bert-Hierarchical-Softmax-Chinese-Text-Classification/blob/master/data/train.txt

> @SCHENLIU
> can you show some samples of the dataset? If you provide some sample, I can understand the code more clearly, and quickly modify your code for my own experiments

**Comment by w5688414** [comment]
thanks @SCHENLIU
